export default {
  zh: {
    chartView: {
      All: '全部',
      RunningStatus: '运行状况',
      Normal: '正常',
      Protection: '保护',
      Fault: '故障',
      Offline: '脱机',
      SystemData: '系统数据',
      GenerationCapacity: "发电量",
      PowerTransmissionNetwork: "送电上网",
      SpontaneousSelfUseRatio: '自发自用比',
      SelfSufficiencyRatio: '自给自足比',
      StorageCapacity: '存储电量',
      ElectricityWithdrawalFromPowerGrid: '电网取电量',
      InstalledCapacity: '装机容量',
      DeviceStatus: "设备状态",
      SystemSN: "系统S/N",
      Desc: "备注",
      UserName: "用户名",
      License: "License",
      CountryRegion: "国家/地区",
      Postcode: '邮编',
      BMSSoftwareVersionNumber: "BMS软件版本号",
      EMSSoftwareVersionNumber: "EBMS软件版本号",
      QueryMode: "查询方式",
      PleaseEnterTheContent: "请输入内容",
      COUNTRYAREA: "国家/地区",
      SN: "S/N",
      SYSTEMSTATUS: "设备状态",
      BMS: "BMS",
      EMS: "EMS",
      BATTERY: "电池",
      INVERTER: "逆变器",
      ACH: "AC/DC/HYBRID",
      TYPE: "TYPE",
      LICENSENO: "LICENES NO.",
      INSTALLERCOMPANY: "安装公司",
      INSTALLATIONDATE: "安装时间",
      REMARK: "备注"

    }
  },
  en: {
    chartView: {
      All: 'All',
      RunningStatus: 'Running Status',
      Normal: 'Normal',
      Protection: 'Protection',
      Fault: 'Fault',
      Offline: 'Offline',
      SystemData: 'System Data',
      GenerationCapacity: "Generation Capacity",
      PowerTransmissionNetwork: "Power Transmission Network",
      SpontaneousSelfUseRatio: 'SpontaneousSelfUseRatio',
      SelfSufficiencyRatio: 'SelfSufficiencyRatio',
      StorageCapacity: 'StorageCapacity',
      ElectricityWithdrawalFromPowerGrid: 'ElectricityWithdrawalFromPowerGrid',
      InstalledCapacity: 'Installed Capacity',
      DeviceStatus: "Device Status",
      SystemSN: "S/N",
      Desc: "Remark",
      UserName: "UserName",
      License: "License NO.",
      CountryRegion: "Country/Area",
      Postcode: 'Zip Code',
      BMSSoftwareVersionNumber: "BMS Firmware Version",
      EMSSoftwareVersionNumber: "EMS Firmware Version",
      QueryMode: "Query Mode",
      PleaseEnterTheContent: " Please enter the content ",
      COUNTRYAREA: "COUNTRY/AREA",
      SN: "S/N",
      SYSTEMSTATUS: "SYSTEM STATUS",
      BMS: "BMS",
      EMS: "EMS",
      BATTERY: "BATTERY",
      INVERTER: "INVERTER",
      ACH: "AC/DC/HYBRID",
      TYPE: "TYPE",
      LICENSENO: "LICENSE NO.",
      INSTALLERCOMPANY: "INSTALLER COMPANY",
      INSTALLATIONDATE: "INSTALLATION DATE",
      REMARK: "REMARK"
    }
  },
  es: {
    chartView: {
      RunningStatus: 'RunningStatus'
    }
  }
}
